### PR TITLE
Cleanup r1

### PR DESCRIPTION
**Pull request by native-api**
This fixes and cleans up dockerfiles.
Let's get this over with.

### CODE REVIEW

**Comment by abhiTronix** [comment]
@native-api Thanks so much for this, but we need some additional changes as you remove `libjpeg-turbo` too.

**Comment by native-api** [comment]
No need for changes. The build logic will detect that relevant envvars are no longer present and use the one bundled with OpenCV.
You can delete the corresponding logic from `setup.py` altogether if you'd like to but it's not strictly necessary atm.

**Comment by native-api** [comment]
I deleted libjpeg-turbo from dockerfile because it was failing the build, see commit message.

**Comment by abhiTronix** [comment]
@native-api **Change this part [here from `setup.py`](https://github.com/native-api/opencv-python/blob/88597ed1d6acde9673a667cee31de818330f19cb/setup.py#L136) which redirects OpenCV to use custom jpeg libs:**
```python
if all(v in os.environ for v in ('JPEG_INCLUDE_DIR', 'JPEG_LIBRARY')):
            cmake_args += [
                "-DBUILD_JPEG=OFF",
                "-DJPEG_INCLUDE_DIR=%s" % os.environ['JPEG_INCLUDE_DIR'],
                "-DJPEG_LIBRARY=%s" % os.environ['JPEG_LIBRARY']
            ]
```
**to**

```python
 cmake_args += ["-DBUILD_JPEG=ON"]
```

**Or simply just remove it entirely, as `"-DBUILD_JPEG=ON"` is set by default in OpenCV cmake .**

**Comment by abhiTronix** [comment]
@native-api **This change is very important as build will fail if no jpeg libs are found.**

**Comment by native-api** [comment]
```python
if all(v in os.environ for v in ('JPEG_INCLUDE_DIR', 'JPEG_LIBRARY')):
```
this ensures that a custom JPEG library is only used if `JPEG_INCLUDE_DIR` and `JPEG_LIBRARY` envvars are present.

**Comment by abhiTronix** [comment]
> if all(v in os.environ for v in ('JPEG_INCLUDE_DIR', 'JPEG_LIBRARY')):
> this ensures that a custom JPEG library is only used if JPEG_INCLUDE_DIR and JPEG_LIBRARY envvars are present.

Yes, but we just removed it(i.e. libjpeg-turbo), so no jpeg support will be present in final build which is dangerous.

**Comment by abhiTronix** [comment]
@native-api see my comment here: https://github.com/skvark/opencv-python/issues/204#issuecomment-516444192

**OpenCV itself provide optimized libjpeg-turbo libs starting from this PR:** opencv/opencv#11497 

**Therefore we can safely remove custom jpeg part from cmake, In this way OpenCV will use its own optimized `libjpeg-turbo` libraries during build.**

**Comment by native-api** [comment]
As it is now, the bundled jpeg-turbo is already used, I checked:

```
--   Media I/O: 
--     ZLib:                        /lib/libz.so (ver 1.2.3)
--     JPEG:                        libjpeg-turbo (ver 2.0.2-62)
<...>
[  4%] Built target libtiff
[  9%] Built target libjpeg-turbo
[  5%] Built target libpng
<...>
```

**Comment by abhiTronix** [comment]
> As it is now, the bundled jpeg-turbo is already used, I checked:
> 
> --   Media I/O: 
> --     ZLib:                        /lib/libz.so (ver 1.2.3)
> --     JPEG:                        libjpeg-turbo (ver 2.0.2-62)
> <...>
> [  4%] Built target libtiff
> [  9%] Built target libjpeg-turbo
> [  5%] Built target libpng
> <...>


@native-api It normally doesn't happens, but if it did , then it may've fallen back to building `libjpeg-turbo`  if no jpeg header files/libs are found on the path specified. But to be on safe side I suggest to make this change otherwise I'll merge it, what's your opinion?

**Comment by native-api** [comment]
If you can't understand why there's no problem due to https://github.com/abhiTronix/opencv-python/pull/4#issuecomment-518764737 , just trust me on this.

**Comment by abhiTronix** [comment]
@native-api ooh, I misread that comment. My apologies. I'll merge it.

**Pull request merged**
