### PR TITLE
fix trivial issues as of 8fc6035dfbe6f07c13882c773e62fb8775dd736b

### PR DESCRIPTION
**Pull request by native-api**

### CODE REVIEW

**Comment by abhiTronix** [comment]
### Wrong PR!

**It's working all fine here:**

```shell
bash-3.2# yum install git -y
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package git.i386 0:1.8.2.3-1.el5 set to be updated
--> Processing Dependency: perl-Git = 1.8.2.3-1.el5 for package: git
--> Processing Dependency: rsync for package: git
--> Processing Dependency: perl(Term::ReadKey) for package: git
--> Processing Dependency: perl(Git) for package: git
--> Processing Dependency: perl(Error) for package: git
--> Processing Dependency: openssh-clients for package: git
--> Running transaction check
---> Package openssh-clients.i386 0:4.3p2-82.el5 set to be updated
--> Processing Dependency: openssh = 4.3p2-82.el5 for package: openssh-clients
--> Processing Dependency: libfipscheck.so.1 for package: openssh-clients
---> Package perl-Error.noarch 1:0.17010-1.el5 set to be updated
---> Package perl-Git.i386 0:1.8.2.3-1.el5 set to be updated
---> Package perl-TermReadKey.i386 0:2.30-4.el5 set to be updated
---> Package rsync.i386 0:3.0.6-6.el5_11 set to be updated
--> Running transaction check
---> Package fipscheck-lib.i386 0:1.2.0-1.el5 set to be updated
--> Processing Dependency: /usr/bin/fipscheck for package: fipscheck-lib
---> Package openssh.i386 0:4.3p2-82.el5 set to be updated
--> Running transaction check
---> Package fipscheck.i386 0:1.2.0-1.el5 set to be updated
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================
 Package                                               Arch                                        Version                                               Repository                                    Size
============================================================================================================================================================================================================
Installing:
 git                                                   i386                                        1.8.2.3-1.el5                                         epel                                          16 M
Installing for dependencies:
 fipscheck                                             i386                                        1.2.0-1.el5                                           base                                          13 k
 fipscheck-lib                                         i386                                        1.2.0-1.el5                                           base                                         6.7 k
 openssh                                               i386                                        4.3p2-82.el5                                          base                                         291 k
 openssh-clients                                       i386                                        4.3p2-82.el5                                          base                                         455 k
 perl-Error                                            noarch                                      1:0.17010-1.el5                                       epel                                          26 k
 perl-Git                                              i386                                        1.8.2.3-1.el5                                         epel                                          46 k
 perl-TermReadKey                                      i386                                        2.30-4.el5                                            epel                                          32 k
 rsync                                                 i386                                        3.0.6-6.el5_11                                        updates                                      338 k

Transaction Summary
============================================================================================================================================================================================================
Install       9 Package(s)
Upgrade       0 Package(s)

Total download size: 17 M
Downloading Packages:
(1/9): fipscheck-lib-1.2.0-1.el5.i386.rpm                                                                                                                                            | 6.7 kB     00:00     
(2/9): fipscheck-1.2.0-1.el5.i386.rpm                                                                                                                                                |  13 kB     00:00     
(3/9): perl-Error-0.17010-1.el5.noarch.rpm                                                                                                                                           |  26 kB     00:00     
(4/9): perl-TermReadKey-2.30-4.el5.i386.rpm                                                                                                                                          |  32 kB     00:00     
(5/9): perl-Git-1.8.2.3-1.el5.i386.rpm                                                                                                                                               |  46 kB     00:00     
(6/9): openssh-4.3p2-82.el5.i386.rpm                                                                                                                                                 | 291 kB     00:01     
(7/9): rsync-3.0.6-6.el5_11.i386.rpm                                                                                                                                                 | 338 kB     00:01     
(8/9): openssh-clients-4.3p2-82.el5.i386.rpm                                                                                                                                         | 455 kB     00:01     
(9/9): git-1.8.2.3-1.el5.i386.rpm                                                                                                                                                    |  16 MB     00:45     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                       317 kB/s |  17 MB     00:55     
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : perl-Error                                                                                                                                                                           1/9 
  Installing     : perl-TermReadKey                                                                                                                                                                     2/9 
  Installing     : rsync                                                                                                                                                                                3/9 
  Installing     : fipscheck-lib                                                                                                                                                                        4/9 
  Installing     : openssh                                                                                                                                                                              5/9 
  Installing     : openssh-clients                                                                                                                                                                      6/9 
  Installing     : fipscheck                                                                                                                                                                            7/9 
  Installing     : git                                                                                                                                                                                  8/9 
  Installing     : perl-Git                                                                                                                                                                             9/9 

Installed:
  git.i386 0:1.8.2.3-1.el5                                                                                                                                                                                  

Dependency Installed:
  fipscheck.i386 0:1.2.0-1.el5        fipscheck-lib.i386 0:1.2.0-1.el5  openssh.i386 0:4.3p2-82.el5  openssh-clients.i386 0:4.3p2-82.el5  perl-Error.noarch 1:0.17010-1.el5  perl-Git.i386 0:1.8.2.3-1.el5 
  perl-TermReadKey.i386 0:2.30-4.el5  rsync.i386 0:3.0.6-6.el5_11      

Complete!
```

**Comment by native-api** [comment]
Since `manylinux1` provides its own source-built version of `git`, installing `git` is unnecessary regardless of whether it works of not.

**Comment by native-api** [comment]
Since `manylinux1` provides its own source-built version of `git` in `/usr/local` -- which as such overrides anything you install with `yum` -- installing `git` is unnecessary and has no effect -- regardless of whether it works of not.

**Comment by abhiTronix** [comment]
**@native-api https://github.com/docker-32bit/ubuntu/issues/12 This what is causing this behavior. It hasn't been fixed yet by docker devs**

**Workaround:** add `ENTRYPOINT ["linux32", "--"]` to i686 in 32-bit images. Here's the source for this fix: https://github.com/conan-io/conan/issues/2552#issuecomment-370503326

**Pull request closed without merging**
